- src/sass/components/_button.scss
Added styles for modal buttons
> Updated _button.scss

- src/partials/products.html
- src/sass/layout/_products.scss
> Add layout + css for Products section

- src/partials/advantages.html
- src/sass/layout/_advantages.scss
> advantages html, css

- src/partials/about.html
> Update HTML + Slyles

- src/partials/products.html
- src/sass/layout/_products.scss
Adaptive for <480px
Added fonts for section texts
Added animation for arrow icons
> Added adaptive design + fonts

- src/partials/modal-windows.html
- src/sass/components/_custom-checkbox.scss
- src/sass/components/_modal-elements.scss
Оптимізувала картинки під ретину на модалках, додала тіні,
> fixed bugs

- src/sass/layout/_hero.scss
> add styles to hero

- src/sass/layout/_hero.scss
Please check the button and the container
> buttons and container

- src/partials/footer.html
- src/sass/layout/_footer.scss
> Добавляет footer

- src/partials/about.html
- src/sass/components/_button.scss
- src/sass/layout/_about.scss
Прикрутил кнопку, добавил галку в кнопку коровки с нашего спрайта.
> Update section about svg

- src/partials/about.html
- src/sass/components/_button.scss
- src/sass/layout/_about.scss
Reverts Ishchenko-Oleksii/team-project20#40
> Revert "Update section about svg"

- src/sass/components/_button.scss
- src/sass/layout/_about.scss
Забирал пока изменения scss section about. Сделаю еще ветку и туда залью изменения по html.
> section about fix scss

- src/sass/layout/_footer.scss
при ховере иконка уменьшается до 32х32px;
при фокусе - увеличивается до 38х38px.
> иконки под ховер и фокус

- src/partials/header.html
- src/sass/layout/_header.scss
В HTML файле добавлена svg-иконка ">" в кнопке;
В SCSS файле добавлены стили для иконки на кнопке; сделано выезжающее меню бургера на таблете и мобильном;
Остались якоря, но похоже не на всех секциях есть id.
> доделана кнопка и бургер

- src/partials/hero.html
- src/sass/layout/_hero.scss
Новая ветка, предыдущий реквест ты удалишь? Спасибо
> new branch with pictures

- src/partials/hero.html
- src/sass/layout/_hero.scss
Снова подвинула картинки и исправила к ним адреса.
> Pictures (tablet, mob)_scss_html

- src/sass/components/_button.scss
- src/sass/layout/_advantages.scss
- src/sass/layout/_products.scss
1. Змінила беграунд бай нав
2. розмір заголовку у продуктах
3. розмір тексту в адвантаджес
4. бордер на кнопках
> Advantages

- src/partials/hero.html
- src/sass/layout/_hero.scss
Внесла правки в код Html (по ошибкам валидатора)
> html corrections

- src/index.html
- src/modal-btns-disabled.js
- src/partials/modal-windows.html
1) added Submit disabled="" (file /partials/modal-windows.html) 
2) added script modal-btns-disabled.js
3) scripts enabled in file index.html (main script + jQuery lib)
> Added button disable scripts

- src/partials/hero.html
Исправила кнопки как просто ссылки.
> new branch

- src/sass/base/_common.scss
> add link transition

- src/sass/components/_button.scss
> add transition button

- src/sass/layout/_hero.scss
> without transition
